# Generated by Django 4.2.7 on 2024-01-06 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0002_user_is_verificate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Biography",
            fields=[
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("town", models.CharField(blank=True, max_length=100, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="image/avatars/%Y"
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=2000, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Biographys",
            },
        ),
    ]
