# Generated by Django 4.2.7 on 2024-02-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0002_story"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="rank",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
